In [3]:
import numpy as np

x = np.random.randn(100)
y = np.random.randn(100)

#f = np.polyfit(x , y , 3)
f = np.polyfit(x , y , 2)
p = np.poly1d(f)

In [4]:
print(p)

         2
0.02283 x - 0.1723 x + 0.1683


In [6]:
from sklearn.preprocessing import PolynomialFeatures
import seaborn as sns
flights = sns.load_dataset("flights")
pr = PolynomialFeatures(degree = 2 , include_bias = False)
x_polly = pr.fit_transform(flights[['year','passengers']])
print(x_polly)

[[1.949000e+03 1.120000e+02 3.798601e+06 2.182880e+05 1.254400e+04]
 [1.949000e+03 1.180000e+02 3.798601e+06 2.299820e+05 1.392400e+04]
 [1.949000e+03 1.320000e+02 3.798601e+06 2.572680e+05 1.742400e+04]
 [1.949000e+03 1.290000e+02 3.798601e+06 2.514210e+05 1.664100e+04]
 [1.949000e+03 1.210000e+02 3.798601e+06 2.358290e+05 1.464100e+04]
 [1.949000e+03 1.350000e+02 3.798601e+06 2.631150e+05 1.822500e+04]
 [1.949000e+03 1.480000e+02 3.798601e+06 2.884520e+05 2.190400e+04]
 [1.949000e+03 1.480000e+02 3.798601e+06 2.884520e+05 2.190400e+04]
 [1.949000e+03 1.360000e+02 3.798601e+06 2.650640e+05 1.849600e+04]
 [1.949000e+03 1.190000e+02 3.798601e+06 2.319310e+05 1.416100e+04]
 [1.949000e+03 1.040000e+02 3.798601e+06 2.026960e+05 1.081600e+04]
 [1.949000e+03 1.180000e+02 3.798601e+06 2.299820e+05 1.392400e+04]
 [1.950000e+03 1.150000e+02 3.802500e+06 2.242500e+05 1.322500e+04]
 [1.950000e+03 1.260000e+02 3.802500e+06 2.457000e+05 1.587600e+04]
 [1.950000e+03 1.410000e+02 3.802500e+06 2.74950